### ISSUE TITLE
ISSUE-139: fatal error: pulsar/c/message.h: No such file or directory

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar-client-node#87]
Original Issue: apache/pulsar-client-node#139 

---

I'm using Ubuntu 18.04.4，and I install Pulsar C++ client by apt install ./apache-pulsar-client*.deb, and  the file libpulsar.so.2.7.0 and libpulsarnossl.so.2.7.0 are in the /usr/lib path. but when I use npm to install pulsar-client package, I still got the following error:
`
In file included from ../src/addon.cc:20:0:
../src/Message.h:24:10: fatal error: pulsar/c/message.h: No such file or directory
 #include <pulsar/c/message.h>
          ^~~~~~~~~~~~~~~~~~~~
`

**Comment by RobertLowe** [comment]
Solution: https://github.com/apache/pulsar-client-node/issues/139#issuecomment-892378724 

Make you you make the correct targets and install.
